"""
Generate docs/compatibility.md by running tests/compat_checks.py against every
configured catalog. Configure REST catalogs with the environment variables
described in tests/test_catalog_compat.py.

    python scripts/compat_matrix.py > docs/compatibility.md
"""

import datetime
import importlib.metadata
import sys
import tempfile
import traceback
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from iceframe import IceFrame  # noqa: E402
from tests.compat_checks import CHECKS, CatalogLacksFeature, catalogs_from_env  # noqa: E402


def main() -> None:
    root = tempfile.mkdtemp(prefix="iceframe-matrix-")
    catalogs = catalogs_from_env(root)
    results: dict[str, dict[str, str]] = {}
    notes: list[str] = []
    for label, config in catalogs.items():
        ice = IceFrame(config)
        ns = f"matrix_{uuid.uuid4().hex[:8]}"
        ice.create_namespace(ns)
        results[label] = {}
        for check, fn in CHECKS.items():
            try:
                fn(ice, ns, tempfile.mkdtemp(dir=root))
                results[label][check] = "Yes"
            except CatalogLacksFeature:
                results[label][check] = "Catalog lacks it"
            except Exception as e:
                notes.append(
                    f"- **{check} on {label}:** `{type(e).__name__}: {str(e).splitlines()[0][:200]}`"
                )
                results[label][check] = f"No ({len(notes)})"
                traceback.print_exc(file=sys.stderr)

    versions = ", ".join(
        f"{pkg} {importlib.metadata.version(pkg)}"
        for pkg in ("iceframe", "pyiceberg", "polars", "pyarrow")
    )
    print("# Catalog compatibility\n")
    print(
        "Generated by `scripts/compat_matrix.py`, which runs the checks in "
        "`tests/compat_checks.py` against each catalog. Every cell is an observed "
        "result, not a claim.\n"
    )
    print(f"Last run: {datetime.date.today().isoformat()} with {versions}.\n")
    labels = list(results)
    print("| Feature | " + " | ".join(labels) + " |")
    print("|---|" + "---|" * len(labels))
    for check in CHECKS:
        print(f"| {check} | " + " | ".join(results[label][check] for label in labels) + " |")
    if notes:
        print("\n## Failures\n")
        print("\n".join(f"{i}. {n[2:]}" for i, n in enumerate(notes, 1)))


if __name__ == "__main__":
    main()
